name: secure_device_control
description: Minimal Phase 8 skeleton for Secure Device Control mobile app.
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^10.0.0
  cryptography: ^2.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
